# Generated by Django 4.0.4 on 2022-05-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_title', models.CharField(max_length=50)),
                ('about_us_body', models.TextField(max_length=200)),
                ('mission_and_vision_title', models.CharField(max_length=50)),
                ('mission_and_vision_body', models.CharField(max_length=200)),
                ('our_team_description', models.CharField(max_length=100)),
                ('name_of_team_leader', models.CharField(max_length=50)),
                ('name_of_team_leader_title', models.CharField(max_length=50)),
                ('leader_description', models.CharField(max_length=50)),
            ],
        ),
    ]
