# Generated by Django 4.0.4 on 2022-05-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='leader_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name_of_team_leader',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name_of_team_leader_title',
        ),
        migrations.AlterField(
            model_name='about',
            name='about_us_body',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_us_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission_and_vision_body',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission_and_vision_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='our_team_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
