# Generated by Django 4.0.4 on 2022-05-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_about_leader_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_us_title_image',
            field=models.ImageField(blank=True, upload_to='images/about'),
        ),
        migrations.AddField(
            model_name='about',
            name='mission_and_vision_image',
            field=models.ImageField(blank=True, upload_to='images/about'),
        ),
    ]
