# Generated by Django 4.0.4 on 2022-05-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_author_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slider',
            field=models.BooleanField(default=False),
        ),
    ]
