# Generated by Django 4.0.4 on 2022-05-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_about_about_us_title_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_team_leader', models.CharField(blank=True, max_length=50, null=True)),
                ('mission_and_vision_image', models.ImageField(blank=True, upload_to='images/leader')),
                ('name_of_team_leader_title', models.CharField(blank=True, max_length=50, null=True)),
                ('leader_description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
