# Generated by Django 4.0.4 on 2022-05-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_teamleader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamleader',
            old_name='mission_and_vision_image',
            new_name='name_of_team_leader_image',
        ),
    ]
